version: "3.8"

services:
  gap_frontend:
    container_name: gap_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Exclude the .next directory from being overridden
      - .:/app:cached
      - /app/node_modules/
      - /app/.next
    networks:
      - gap_network
    environment:
      - NODE_ENV=production

networks:
  gap_network:
