name: Next.js CI/CD with Vercel

on:
  push:
    branches:
      - main
      - add-ci
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: node_modules
        path: node_modules

  build-and-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print current directory
      run: pwd

    - name: List contents after download
      run: ls

    - name: Download node_modules
      uses: actions/download-artifact@v4
      with:
        name: node_modules
        path: node_modules

    - name: List contents after download
      run: ls

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Deploy to Vercel
  #     uses: amondnet/vercel-deployment@v1
  #     with:
  #       vercel_token: ${{ secrets.VERCEL_TOKEN }}
  #       vercel_project_id: YOUR_VERCEL_PROJECT_ID
