name: GAP FE CI

on:
  push:
    branches:
      - developer

  pull_request:
    branches:
      - developer

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: Set executable permissions for next binary
        run: chmod +x ./node_modules/next/dist/bin/next

      - name: Build
        run: npm run build:ci

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: Run tests
        run: npm run test

  deploy-to-vercel:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      # - name: Manual approval
      #   id: manual-approval
      #   run: echo "Ready for deployment? Approve or reject this workflow run by commenting on the pull request."

      # - name: Check if approved
      #   if: steps.manual-approval.outputs.result == 'approve'
      #   run: exit 0
      - name: Set CI name
        run: git config --global user.name "gap-github-ci"
      
      - name: Set CI email
        run: git config --global user.email "gap-github-ci@gap.de"

      - name: cwd
        run: pwd

      - name: ls current directory
        run: ls -la

      - name: Checkout code
        if: steps.manual-approval.outputs.result == 'approve'
        uses: actions/checkout@v2
        with:
          ref: 'developer'
          path: 'gap-next-fe'

      - name: cwd 2
        run: pwd

      - name: ls current directory 2
        run: ls -la


      - name: Deploy to Staging on Vercel
        # if: steps.manual-approval.outputs.result == 'approve'
        run:  npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes -S gap-team
